openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Returns a simple greeting
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              example: { message: "Hello, World!" }
